module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__64[64];
      struct Array64 {
        octet__64 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
