module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__32[32];
      struct Array32 {
        octet__32 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
