module performance_test {
  module msg {
    module __plugin__ {
      // 8 bytes for time
      // 8 bytes for id
      // 61440 - 16 = 61424
      typedef octet octet__61440[61424];
      struct Array60k {
        octet__61440 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
